# Generated by Django 6.0.3 on 2026-06-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=90)),
                ('total', models.PositiveIntegerField()),
                ('precio', models.PositiveIntegerField()),
                ('caption', models.TextField(verbose_name='Descripcion')),
                ('generalidades', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['nombre'],
            },
        ),
    ]
