# Generated by Django 6.0.3 on 2026-06-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='altocm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Alto (cm)'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='altoin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Alto (pulgadas)'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='anchocm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Ancho (cm)'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='anchoin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Ancho (cm)'),
        ),
    ]
