# Generated by Django 6.0.3 on 2026-06-11 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_servicio_altocm_servicio_altoin_servicio_anchocm_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='evento',
            new_name='Eventos',
        ),
        migrations.RenameModel(
            old_name='Servicio',
            new_name='servicio',
        ),
    ]
