# Generated by Django 6.0.3 on 2026-06-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_rename_evento_eventos_rename_servicio_servicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=90)),
                ('total', models.PositiveIntegerField()),
                ('precio', models.PositiveIntegerField()),
                ('anchoin', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Ancho (cm)')),
                ('altoin', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Alto (pulgadas)')),
                ('anchocm', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Ancho (cm)')),
                ('altocm', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Alto (cm)')),
                ('caption', models.TextField(verbose_name='Descripcion')),
                ('generalidades', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.RenameModel(
            old_name='Eventos',
            new_name='evento',
        ),
    ]
