# Generated by Django 6.0.3 on 2026-06-12 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_servicio_rename_eventos_evento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='servicio',
            new_name='serviciop',
        ),
    ]
