# Generated by Django 6.0.3 on 2026-06-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0006_rename_servicio_serviciop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciop',
            name='generalidades',
            field=models.TextField(verbose_name='Link a WhatsApp'),
        ),
    ]
