# Generated by Django 6.0.3 on 2026-06-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0007_alter_serviciop_generalidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciop',
            name='categoria',
            field=models.CharField(max_length=120, null=True, verbose_name='Categoría'),
        ),
    ]
