# Generated by Django 6.0.3 on 2026-06-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_serviciop_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciop',
            name='anchoin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Ancho (pulgadas)'),
        ),
    ]
