# Generated by Django 6.0.3 on 2026-06-15 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_alter_serviciop_anchoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviciopop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=120, null=True, verbose_name='Categoría')),
                ('precio', models.PositiveIntegerField()),
                ('caption', models.TextField(verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.serviciop')),
            ],
            options={
                'verbose_name': 'Servicio destacado',
                'verbose_name_plural': 'Servicios populares',
                'ordering': ['nombre'],
            },
        ),
    ]
