# Generated by Django 6.0.3 on 2026-06-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0010_serviciopop'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciopop',
            name='foto',
            field=models.ImageField(blank=True, height_field=200, upload_to='', width_field=360),
        ),
    ]
