# Generated by Django 6.0.3 on 2026-06-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0011_serviciopop_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciop',
            name='altocm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Alto (cm)'),
        ),
        migrations.AlterField(
            model_name='serviciop',
            name='altoin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Alto (pulgadas)'),
        ),
        migrations.AlterField(
            model_name='serviciop',
            name='anchocm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ancho (cm)'),
        ),
        migrations.AlterField(
            model_name='serviciop',
            name='anchoin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ancho (pulgadas)'),
        ),
        migrations.AlterField(
            model_name='serviciopop',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
