# Generated by Django 6.0.3 on 2026-06-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0012_alter_serviciop_altocm_alter_serviciop_altoin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=90)),
                ('alineade', models.CharField(max_length=90)),
                ('contenido', models.TextField()),
                ('caption', models.TextField(verbose_name='Descripcion')),
                ('generalidades', models.TextField()),
                ('imagen', models.ImageField(blank=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['nombre'],
            },
        ),
        migrations.DeleteModel(
            name='evento',
        ),
    ]
