# Generated by Django 6.0.3 on 2026-06-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0013_eventop_delete_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventop',
            name='alineadep',
            field=models.CharField(blank=True, max_length=90, verbose_name='Clase image'),
        ),
    ]
