# Generated by Django 6.0.3 on 2026-06-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0014_eventop_alineadep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventop',
            name='alineade',
        ),
        migrations.RemoveField(
            model_name='eventop',
            name='alineadep',
        ),
    ]
