# Generated by Django 6.0.1 on 2026-06-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0015_remove_eventop_alineade_remove_eventop_alineadep'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventop',
            name='pronombre',
            field=models.CharField(default=''),
        ),
    ]
