# Generated by Django 6.0.3 on 2026-06-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0016_eventop_pronombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='paquetes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('contenido', models.TextField()),
                ('costo', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paquete de graduación',
                'verbose_name_plural': 'Paquetes de graduación',
            },
        ),
    ]
