# Generated by Django 6.0.3 on 2026-06-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0017_paquetes'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquetes',
            name='mensaje',
            field=models.TextField(blank=True, verbose_name='Link a WhatsApp'),
        ),
        migrations.AlterField(
            model_name='paquetes',
            name='costo',
            field=models.PositiveIntegerField(verbose_name='Precio'),
        ),
    ]
