# Generated by Django 6.0.3 on 2026-06-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0018_paquetes_mensaje_alter_paquetes_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquetes',
            name='imagen_movil',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
