# Generated by Django 6.0.1 on 2026-06-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0019_paquetes_imagen_movil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciopop',
            name='categoria',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='serviciopop',
            name='precio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
